AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template demonstrating canary Lambda deploys with CodeDeploy

Parameters:
  PublishAlias:
    Type: String
    Description: SAM/Lambda deploy alias name (eg. prod)
    Default: Prod

Globals:
  Function:
    Timeout: 30

Resources:
  RootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: python3.7
      AutoPublishAlias: !Ref PublishAlias
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Alarms:
          - !Ref AliasErrorMetricGreaterThanZeroAlarm
        Hooks:
          PreTraffic: !Ref PreTrafficFunction
      Events:
        GetRoot:
          Type: Api
          Properties:
            Path: /
            Method: get

  PreTrafficFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoAPI_preTrafficHook
      CodeUri: app/
      Handler: pre_traffic_hook.handler
      Runtime: python3.7
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - codedeploy:PutLifecycleEventHookExecutionStatus
              Resource: !Sub arn:${AWS::Partition}:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Ref RootFunction.Version
      DeploymentPreference:
        Enabled: false
        Role: ""
      Environment:
        Variables:
          CurrentVersion: !Ref RootFunction.Version

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub ${RootFunction}:${PublishAlias}
        - Name: FunctionName
          Value: !Ref RootFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

Outputs:
  DemoApi:
    Description: API Gateway endpoint URL for Prod stage for Root function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  RootFunction:
    Description: Root Lambda Function ARN
    Value: !GetAtt RootFunction.Arn
  RootFunctionIamRole:
    Description: Implicit IAM Role created for Root function
    Value: !GetAtt RootFunctionRole.Arn
